---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: csi-driver-smb-alert
  namespace: flux-system
spec:
  summary: "CSI Driver SMB"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: csi-driver-smb
    - kind: HelmChart
      name: '*'
      namespace: csi-driver-smb
    - kind: HelmRelease
      name: '*'
      namespace: csi-driver-smb
