---
apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 1h
  timeout: 10m
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
      version: 0.10.5
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: authelia
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    pod:
      kind: 'Deployment'
      annotations:
        reloader.stakater.com/auto: "true"
      selectors:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: 'In'
                        values:
                          - authelia
                  topologyKey: kubernetes.io/hostname
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      extraVolumeMounts:
        - name: config-file
          mountPath: /config/users_database.yml
          subPath: users_database.yml
      extraVolumes:
        - name: config-file
          configMap:
            name: authelia-user-config
      resources:
        requests:
          cpu: 1m
          memory: 53Mi
        limits:
          cpu: ~
          memory: 53Mi
    configMap:
      access_control:
        default_policy: 'one_factor'
      authentication_backend:
        file:
          enabled: true
      session:
        cookies:
          - subdomain: auth
            domain: homelab-peej.dev
        redis:
          enabled: true
          deploy: true
          host: 'authelia-authelia-redis-master.authelia.svc.cluster.local'
      notifier:
        filesystem:
          enabled: true
      storage:
        local:
          enabled: true
      password_policy:
        sdandard:
          enabled: true
          min_length: 32
          require_uppercase: true
          require_lowercase: true
          require_number: true
          require_special: true
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
    redis:
      master:
        resources:
          requests:
            cpu: 12m
            memory: 12Mi
          limits:
            cpu: ~
            memory: 12Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: replace
                path: /spec/replicas
                value: 2
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-private
  namespace: authelia
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.homelab-peej.dev
      secretName: authelia-internal-tls-secret
  rules:
    - host: auth.homelab-peej.dev
      http:
        paths:
          - backend:
              service:
                name: authelia-authelia
                port:
                  number: 80
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-internal-certificate
  namespace: authelia
spec:
  secretName: authelia-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - auth.homelab-peej.dev
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: authelia-alert
  namespace: flux-system
spec:
  summary: "Authelia"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: authelia
    - kind: HelmChart
      name: '*'
      namespace: authelia
    - kind: HelmRelease
      name: '*'
      namespace: authelia
