---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  timeout: 10m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: v1.17.1
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: cert-manager
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    crds:
      enabled: true
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    resources:
      requests:
        cpu: 2m
        memory: 47Mi
      limits:
        memory: 47Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - cert-manager
            topologyKey: "kubernetes.io/hostname"
    prometheus:
      servicemonitor:
        enabled: true
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      resources:
        requests:
          cpu: 1m
          memory: 19Mi
        limits:
          memory: 19Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - webhook
              topologyKey: "kubernetes.io/hostname"
    cainjector:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      resources:
        requests:
          cpu: 1m
          memory: 85Mi
        limits:
          memory: 85Mi
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: cert-manager-alert
  namespace: flux-system
spec:
  summary: "Cert-Manager"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: cert-manager
    - kind: HelmChart
      name: '*'
      namespace: cert-manager
    - kind: HelmRelease
      name: '*'
      namespace: cert-manager
