---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-driver-nfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 1h
  timeout: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      version: 4.11.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: csi-driver-nfs
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: csi-driver-nfs-alert
  namespace: flux-system
spec:
  summary: "CSI Driver NFS"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: csi-driver-nfs
    - kind: HelmChart
      name: '*'
      namespace: csi-driver-nfs
    - kind: HelmRelease
      name: '*'
      namespace: csi-driver-nfs
