---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-driver-smb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: csi-driver-smb
spec:
  interval: 1h
  timeout: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: csi-driver-smb
  namespace: csi-driver-smb
spec:
  chart:
    spec:
      chart: csi-driver-smb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
      version: v1.17.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: csi-driver-smb
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    windows:
      enabled: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: csi-driver-smb-alert
  namespace: flux-system
spec:
  summary: "CSI Driver SMB"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: csi-driver-smb
    - kind: HelmChart
      name: '*'
      namespace: csi-driver-smb
    - kind: HelmRelease
      name: '*'
      namespace: csi-driver-smb
