---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 8h
  timeout: 10m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: node-feature-discovery
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    master:
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 128Mi
    worker:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 5m
          memory: 64Mi
    gc:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 128Mi
    prometheus:
      enable: true
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: node-feature-discovery-alert
  namespace: flux-system
spec:
  summary: "Node Feature Discovery"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: node-feature-discovery
    - kind: HelmChart
      name: '*'
      namespace: node-feature-discovery
    - kind: HelmRelease
      name: '*'
      namespace: node-feature-discovery
