---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 8h
  timeout: 10m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 34.5.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: traefik
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 70
    deployment:
      enabled: true
      kind: Deployment
      revisionHistoryLimit: 3
      annotations:
        reloader.stakater.com/auto: "true"
    resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        memory: 68Mi
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik-dashboard.homelab-peej.dev`)
        entryPoints: ["websecure"]
        middlewares:
          - name: traefik-dashboard-auth
        tls:
          secretName: traefik-dashboard-internal-tls-secret
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ports:
      web:
        port: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 443
    persistence:
      enabled: true
      size: 512Mi
      storageClass: "longhorn"
      accessMode: ReadWriteMany
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: '{{ template "traefik.name" . }}'
                app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
            topologyKey: kubernetes.io/hostname
    service:
      annotations:
        metallb.universe.tf/address-pool: traefik
    experimental:
      plugins:
        fail2ban:
          moduleName: "github.com/tomMoulard/fail2ban"
          version: "v0.8.3"
        geoblock:
          moduleName: "github.com/PascalMinder/geoblock"
          version: "v0.3.2"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-dashboard-auth
  namespace: traefik
spec:
  basicAuth:
    secret: traefik-dashboard-auth-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-internal-certificate
  namespace: traefik
spec:
  secretName: traefik-dashboard-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - traefik-dashboard.homelab-peej.dev
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: traefik-alert
  namespace: flux-system
spec:
  summary: "Traefik"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: traefik
    - kind: HelmChart
      name: '*'
      namespace: traefik
    - kind: HelmRelease
      name: '*'
      namespace: traefik
