---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-internal-certificate
  namespace: mealie
spec:
  secretName: mealie-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.homelab-peej.dev
