apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-clusterissuer
spec:
    acme:
        email: ENC[AES256_GCM,data:WIXjMk5dl5knCl2D7bNa,iv:xzvIcgAboyfZltmY8rtcDITVjC4pE8S0MLcNpz+lxEg=,tag:xgbMBE1h6arvhT5mcqM3Ew==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token
sops:
    lastmodified: "2025-05-10T18:11:06Z"
    mac: ENC[AES256_GCM,data:FBCOWOIVLM5kivDw5CSPMcRo2qF7BddWRfVtdlXRzRJLLF4XQPoZD8sFyS99gFxFU2JO1mhKATXCSn3AkIJ1c3OXWP0ro3eRuqnARURkYImmADb/zrfqV8skoEHoEm9CYrnZ7d0+DbsPxkJxyeVtthNn7kdcRjb8pJK9FJAwTaw=,iv:X9h7k+fr8x6dGRgYgBuavgkqnSEZhlI+8jIlOsuK+/Q=,tag:fQS3e+Fpf6yU7suLHdmQQQ==,type:str]
    pgp:
        - created_at: "2025-05-10T18:11:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZAQ//Vcdab56Jrt15jxRfe7GbLe79opNxBm9A7NLXNpOJZSlX
            PoUSMgRSmVM2pQgAn/e30m51Z3k5uietopovoFtNtQ7gM3QiR9G6sa0ASMhoVY8m
            wMSL9mZu6nu3nkcBjcik2Hx+RihPdqvAZp5Co1c6XuxgMp72a1JJ0g4C+RrbLOOt
            9abK1WguqIFKeZnWupLUkBBp7zos2ZihpBKzhIB0mZeNsfzIVHOAbec1oJr0ZzIo
            HFAyo2cBP+XSZOL8igZTSUuUbWjs+Iy6+kkGKWXLU3N1pCNNus2m9CIlr1pfjOMf
            tKrO8JGTGOyPholwLYvTea5D1BNdAbMXHVLdqs/uzl7rIRS0c3epWMS5zKWHf6al
            urUIkVXDqidBpTxqYgz49gmcsmgoNynQV4gtRs6bUA2eRummPVcgZsxsIAeVhIcE
            jJJGOlZpVVw6zXW+gOxTBLNm2HEh+HEEmWzTkktxQ6FSQzMbIhy/uRML43B5oElG
            NjU9P8xnCq6fJeKUy4I1HnR1CtSLDb1rjetMOGSRVXROF8nXWHKs6NuRy3P5q8HW
            35BLZzWTP/DOHPnTGqmGQ5n7miCUr9DpoGQj2+w7Jc0Mn4VB2aHZ1H42Wr2jbX9q
            Txe/Y7PI3ufulUmXZQhdpxRfIfJV7Zci4AJq++rTRaBEt/14JGyw6LMvGUpUEP7U
            aAEJAhDXACHYtrHFFd8usmq0JZFkhrHX7QqkQI1dEy5/DuSMpemmvTxaoHTf7qFX
            JC0eemyj82pX2xQ8glf4vgoEjlQ9fIzVGpvxQf/E925+CK60WnB4B6mkw1x6Miup
            FEYV0zleEkbC
            =26bS
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: internal-cloudflare-clusterissuer
spec:
    acme:
        email: ENC[AES256_GCM,data:jnh1dMjyNMJ2ryFfHbOG,iv:pRJZII3GaSJDWGKXpOlfSBG8+qmyDEQcUsU7VM9716w=,tag:cPPHxC1a5dX7qzB2/b1GWw==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: internal-cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: internal-cloudflare-api-token-secret
                          key: api-token
sops:
    lastmodified: "2025-05-10T18:11:06Z"
    mac: ENC[AES256_GCM,data:FBCOWOIVLM5kivDw5CSPMcRo2qF7BddWRfVtdlXRzRJLLF4XQPoZD8sFyS99gFxFU2JO1mhKATXCSn3AkIJ1c3OXWP0ro3eRuqnARURkYImmADb/zrfqV8skoEHoEm9CYrnZ7d0+DbsPxkJxyeVtthNn7kdcRjb8pJK9FJAwTaw=,iv:X9h7k+fr8x6dGRgYgBuavgkqnSEZhlI+8jIlOsuK+/Q=,tag:fQS3e+Fpf6yU7suLHdmQQQ==,type:str]
    pgp:
        - created_at: "2025-05-10T18:11:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZAQ//Vcdab56Jrt15jxRfe7GbLe79opNxBm9A7NLXNpOJZSlX
            PoUSMgRSmVM2pQgAn/e30m51Z3k5uietopovoFtNtQ7gM3QiR9G6sa0ASMhoVY8m
            wMSL9mZu6nu3nkcBjcik2Hx+RihPdqvAZp5Co1c6XuxgMp72a1JJ0g4C+RrbLOOt
            9abK1WguqIFKeZnWupLUkBBp7zos2ZihpBKzhIB0mZeNsfzIVHOAbec1oJr0ZzIo
            HFAyo2cBP+XSZOL8igZTSUuUbWjs+Iy6+kkGKWXLU3N1pCNNus2m9CIlr1pfjOMf
            tKrO8JGTGOyPholwLYvTea5D1BNdAbMXHVLdqs/uzl7rIRS0c3epWMS5zKWHf6al
            urUIkVXDqidBpTxqYgz49gmcsmgoNynQV4gtRs6bUA2eRummPVcgZsxsIAeVhIcE
            jJJGOlZpVVw6zXW+gOxTBLNm2HEh+HEEmWzTkktxQ6FSQzMbIhy/uRML43B5oElG
            NjU9P8xnCq6fJeKUy4I1HnR1CtSLDb1rjetMOGSRVXROF8nXWHKs6NuRy3P5q8HW
            35BLZzWTP/DOHPnTGqmGQ5n7miCUr9DpoGQj2+w7Jc0Mn4VB2aHZ1H42Wr2jbX9q
            Txe/Y7PI3ufulUmXZQhdpxRfIfJV7Zci4AJq++rTRaBEt/14JGyw6LMvGUpUEP7U
            aAEJAhDXACHYtrHFFd8usmq0JZFkhrHX7QqkQI1dEy5/DuSMpemmvTxaoHTf7qFX
            JC0eemyj82pX2xQ8glf4vgoEjlQ9fIzVGpvxQf/E925+CK60WnB4B6mkw1x6Miup
            FEYV0zleEkbC
            =26bS
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
