apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-clusterissuer
spec:
    acme:
        email: ENC[AES256_GCM,data:uTYk4Aa7/QNJ2ed8r2Sw,iv:udY6/tOQhG/kS0egjkcy4FmGiBp4O38XraBDCLEhdX0=,tag:h2pO7RyEqr310pMqfLY9xw==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-api-token-secret
                        key: api-token
sops:
    lastmodified: "2025-05-10T18:07:19Z"
    mac: ENC[AES256_GCM,data:eV8rQ2RWFzATAN9dMPZdCAxsrYul3dOCVyYbzbWVAqPeyDMOv5lLcIxHxed/C85eQ7jX/tiSVCU7rzIsxXq2FiEeu/GFuHRh7GmdELlnXcCG3jcrarp/+UJA6Nda2BbhC6RAsEC0XjiwDQPPnrGfmp83ghgZbu3YxoEDBbadrHI=,iv:AmzSvevVZzti/LKyTM190NtINJ/2YIk3eXOhgC9mOHE=,tag:OWq+QmiubmKGd1vCIMcLbw==,type:str]
    pgp:
        - created_at: "2025-05-10T18:07:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZAQ//ShxxWO9sdFJlHJjM2rkpspMW5SX9+jvPj+Xi5R49bjTP
            x/0aCJuu2/0gzLG7u0ejGYLLuohbsXqa7NdJeYnOLDCyo51yEGjB9MnOsb+LHjQ4
            ay+ft5RbdDNxitAZMfH7Vf6daJneDYmAlqfUQxJTZUzfE4q9UH671/Qd8X7AWF7X
            mtSlqgNo++A03IM/8oDmRHtUMVLYjSvW5rAED0hN0VQ+wVPWAr8+TNZqwqmpWsdU
            1DrjM2wUWzafVAh/Sll4HhHY0RRv4hBA4+66CiyH4jfo1h21L34+hPk99+JJaNSh
            Ql3GyFwf87pp7iWHACEh8Zsm9dix3xVGkJ0a9ppnI1sqkhX40ebrlf5og7mtcMqN
            P5Z3NIoaYDNKbD88SQzbcNb5YjkW8KLE+0zzpR6C++Xv046q6JF6CNvu1yvbBUAC
            D3lgdaq5E9tPGt/v2KF22tF1PcBeX44go6OUaSpeltAENwt1ZkXa/ErZz4QOX6j2
            gLnwrXOgXlL9I7K6ffLvTX/V3RZqfIpPr/2H4hizPbg5ecq0S0Rgc7lrzK0xEPqO
            h5a4PCVehXtxhBZdPDUL48EB3khLJUABRB60MkOX5lVzPycOnvElKxTnIB3BEhoT
            XLCkMOr/u1OqURjRgvI+mebX50EIVvhPJD2h+sVfSMHaNVASDryYKsjAtY6O5UHU
            aAEJAhAIbDLgmfUvM9mA1r1qjTSlKPUjmKCHnx0olvFbE6J/IqONwDOScL1q1iJ1
            mlYpOi6Mz5rE/ygJT0qMwt7/FetJ1YFjrPfplj3phyaFlYWO2lWllLppwnXgxNXa
            ds8rtym0Fafm
            =eGbo
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: internal-cloudflare-clusterissuer
spec:
    acme:
        email: ENC[AES256_GCM,data:bpiXzxQ7iMgeAuN3buKX,iv:4ytpVLDbhh/geD3+sx4zyHCS0G7s7K13fRbFLe/x0AM=,tag:beDRQA/bTWpe2Ow6b83NtA==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: internal-cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: internal-cloudflare-api-token-secret
                        key: api-token
sops:
    lastmodified: "2025-05-10T18:07:19Z"
    mac: ENC[AES256_GCM,data:eV8rQ2RWFzATAN9dMPZdCAxsrYul3dOCVyYbzbWVAqPeyDMOv5lLcIxHxed/C85eQ7jX/tiSVCU7rzIsxXq2FiEeu/GFuHRh7GmdELlnXcCG3jcrarp/+UJA6Nda2BbhC6RAsEC0XjiwDQPPnrGfmp83ghgZbu3YxoEDBbadrHI=,iv:AmzSvevVZzti/LKyTM190NtINJ/2YIk3eXOhgC9mOHE=,tag:OWq+QmiubmKGd1vCIMcLbw==,type:str]
    pgp:
        - created_at: "2025-05-10T18:07:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZAQ//ShxxWO9sdFJlHJjM2rkpspMW5SX9+jvPj+Xi5R49bjTP
            x/0aCJuu2/0gzLG7u0ejGYLLuohbsXqa7NdJeYnOLDCyo51yEGjB9MnOsb+LHjQ4
            ay+ft5RbdDNxitAZMfH7Vf6daJneDYmAlqfUQxJTZUzfE4q9UH671/Qd8X7AWF7X
            mtSlqgNo++A03IM/8oDmRHtUMVLYjSvW5rAED0hN0VQ+wVPWAr8+TNZqwqmpWsdU
            1DrjM2wUWzafVAh/Sll4HhHY0RRv4hBA4+66CiyH4jfo1h21L34+hPk99+JJaNSh
            Ql3GyFwf87pp7iWHACEh8Zsm9dix3xVGkJ0a9ppnI1sqkhX40ebrlf5og7mtcMqN
            P5Z3NIoaYDNKbD88SQzbcNb5YjkW8KLE+0zzpR6C++Xv046q6JF6CNvu1yvbBUAC
            D3lgdaq5E9tPGt/v2KF22tF1PcBeX44go6OUaSpeltAENwt1ZkXa/ErZz4QOX6j2
            gLnwrXOgXlL9I7K6ffLvTX/V3RZqfIpPr/2H4hizPbg5ecq0S0Rgc7lrzK0xEPqO
            h5a4PCVehXtxhBZdPDUL48EB3khLJUABRB60MkOX5lVzPycOnvElKxTnIB3BEhoT
            XLCkMOr/u1OqURjRgvI+mebX50EIVvhPJD2h+sVfSMHaNVASDryYKsjAtY6O5UHU
            aAEJAhAIbDLgmfUvM9mA1r1qjTSlKPUjmKCHnx0olvFbE6J/IqONwDOScL1q1iJ1
            mlYpOi6Mz5rE/ygJT0qMwt7/FetJ1YFjrPfplj3phyaFlYWO2lWllLppwnXgxNXa
            ds8rtym0Fafm
            =eGbo
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
