---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy
  namespace: grocy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
