---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
spec:
  schedule: '*/10 * * * *'
  concurrencyPolicy: Forbid
  timeZone: 'America/Chicago'
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: renovate
        spec:
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:41.98
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 850m
                  memory: 1300Mi
                  ephemeral-storage: 2Gi
                limits:
                  memory: 1300Mi
                  ephemeral-storage: 2Gi
              args:
                - homelab-peej/k8s-at-home
                - homelab-peej/ping-server
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_FORK_PROCESSING
                  value: disabled
              envFrom:
                - secretRef:
                    name: renovate-env
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
                readOnlyRootFilesystem: true
                runAsUser: 65534
                runAsGroup: 65534
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          restartPolicy: Never
          volumes:
            - name: tmp
              emptyDir: {}
