---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: '*/10 * * * *'
  concurrencyPolicy: Forbid
  timeZone: 'America/Chicago'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:41.40
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 850m
                  memory: 1300Mi
                limits:
                  memory: 1300Mi
              args:
                - homelab-peej/k8s-at-home
                - homelab-peej/ping-server
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
