# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: default
#   namespace: metallb
# spec:
#   addresses:
#     - 192.168.1.3-192.168.1.10
# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: traefik
#   namespace: metallb
# spec:
#   autoAssign: false
#   addresses:
#     - 192.168.1.2/32
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: default
#   namespace: metallb
# spec:
#   ipAddressPools:
#     - default
#     - traefik
