---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yamllint-runner-set
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: arc-runner-set
  interval: 24h
  values:
    githubConfigUrl: "https://github.com/homelab-peej/"
    githubConfigSecret: arc-token
    maxRunners: 5
    minRunners: 1
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/homelab-peej/yamllint:2.324.0
            command: ["/home/runner/run.sh"]
