---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: cnpg-operator
  namespace: cnpg-operator
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
      version: 0.25.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  values:
    podAnnotations:
      kube-score/ignore: pod-probes-identical # These are set by the chart and not easily configurable
    resources:
      requests:
        cpu: 10m
        memory: 115Mi
        ephemeral-storage: 2Gi
      limits:
        memory: 115Mi
        ephemeral-storage: 2Gi
