---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-internal-certificate
  namespace: linkding
spec:
  secretName: linkding-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - linkding.homelab-peej.dev
