---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: gpu-operator
  namespace: gpu-operator
spec:
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
      version: v25.3.3
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: gpu-operator
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    operator:
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: ~
          memory: 100Mi
    dcgmExporter:
      resources:
        requests:
          cpu: 10m
          memory: 600Mi
        limits:
          memory: 600Mi
    devicePlugin:
      config:
        name: time-slicing-config
        default: any
      resources:
        requests:
          cpu: 2m
          memory: 44Mi
        limits:
          memory: 44Mi
    gfd:
      resources:
        requests:
          cpu: 3m
          memory: 90Mi
        limits:
          memory: 90Mi
    toolkit:
      env:
        - name: CONTAINERD_CONFIG
          value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
      resources:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          memory: 40Mi
    validator:
      resources:
        requests:
          cpu: 2m
          memory: 2Mi
        limits:
          memory: 2Mi
    nfd:
      enabled: false
    driver:
      enabled: false
    migManager:
      enabled: false
    vgpuDeviceManager:
      enabled: false
    vfioManager:
      enabled: false
    sandboxDevicePlugin:
      enabled: false
