apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: ENC[AES256_GCM,data:tuHk2biL39XNnAvD4Zjf,iv:ja5Q2DpmBwCC3rm4+dH5IRZ97h6R0EZV1Tafyk+9vSE=,tag:vMsoBIxVNlqXsoyOuBqWnQ==,type:str]
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
sops:
  lastmodified: "2025-05-10T18:27:57Z"
  mac: ENC[AES256_GCM,data:0eeg3evWQfOcjB2PaTHyZz2Fu+ZD/yGu8fOIn+MWnvOaLagEA919tB5SGZzAOkc8jhbXFO1k/i+N/3al9hY7qZDqabD617/PrBl3z3AeesTcL8yUIRO5MNC8QIlX6ewFDILYiZIQrXAcMkWL4lm9Y7UsVSMzo2Y4Ws/Ol2FNwQs=,iv:6zdV0AKmKrmFVM4dBRYO/mLPm0gRV+9iWY1cvOCu+wA=,tag:yGWmyiTWtYNqyvfG01FGaA==,type:str]
  pgp:
    - created_at: "2025-05-10T18:27:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1q7zTHG2LSZAQ//VBCYfnbX0SOg18DDE55DvNi9Dw8xS+uSMCei2/h99c5M
        9ULIUtARCSI/F7DkG+YGaC88STK24owLsmKTc/ReO4hYTM0bHFjOc3Ze8Hvw7le1
        DtR4M2XAo8S6jmXTyEyhBlXcNx4EBiz7q4O92X2RZVd9oARB5uBHqpvP733dWj1W
        R3Wni4QzXbnbu70boa4tg168kQOk6i3tJ0INi+UZzcIxDJEUDGAoHGR6fPD+3QZL
        gct8ziC5IjSnzwqrHbZUGJSir6OxuQQ0vvqJQ28z/Nn0v7rfTeVTVesfkCfl6nk5
        CvNnGO+LhDmMpYOMPIqj64BfXwps2Ncvxj/HamZ8Y7ErVBNPK4sr18NHyU2fDMXA
        IFj/2F2ztz/aaNQXAb7JSlj8hqe5ZeL5EOsbrFvTKeitYxeIRLm5tWzVbBnHK+Uc
        kBu+KMo0O5z9sPNKTwgcZH350i3Ha37z4kFhakeW1Fe4pBmSrQjUicQhPI8JS9Pk
        OCDQfxBv3Nz6d6c/oLcZXO9exNlv3tdI0oZFOsUbYkidcz3p856ebcVBa0R6VF2c
        mGaoDM2Ky1xtCmlYumviTnJdbFng7cGu40XnwBw8XEL3dqTVtHBQ+PJRBJd/ON54
        fYK+CPQ2Gd52K+Fbsnp4F6zrzSwGLTxjKbb7BzxiqsaU9Jvx0yxDO1eI3Pn2zUnU
        aAEJAhD2VH3bCOm1ylv5VPHEl+QcB97rHeuCS1QiMjZ8Pp3u5M7NNv21A7fpWCc6
        1pOl3kVKPs7ZP4hbLMnlXwhI3Fr8gtpjsitje4Re8zB/LOX4oYST0YwFlCdhtya+
        TZeE17jy5fun
        =+YW7
        -----END PGP MESSAGE-----
      fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
  encrypted_regex: ^(data|stringData|email)$
  version: 3.10.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-cloudflare-clusterissuer
spec:
  acme:
    email: ENC[AES256_GCM,data:9WyOdyojrqGTXxZkQ9tQ,iv:Y7n7EdknGnQYP3kD2zGt/5PUYFEKtQdGBf1vb1AyQ4I=,tag:NFU3LY+dS0ycXoSanGO8Rw==,type:str]
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: internal-cloudflare-clusterissuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: internal-cloudflare-api-token-secret
              key: api-token
sops:
  lastmodified: "2025-05-10T18:27:57Z"
  mac: ENC[AES256_GCM,data:0eeg3evWQfOcjB2PaTHyZz2Fu+ZD/yGu8fOIn+MWnvOaLagEA919tB5SGZzAOkc8jhbXFO1k/i+N/3al9hY7qZDqabD617/PrBl3z3AeesTcL8yUIRO5MNC8QIlX6ewFDILYiZIQrXAcMkWL4lm9Y7UsVSMzo2Y4Ws/Ol2FNwQs=,iv:6zdV0AKmKrmFVM4dBRYO/mLPm0gRV+9iWY1cvOCu+wA=,tag:yGWmyiTWtYNqyvfG01FGaA==,type:str]
  pgp:
    - created_at: "2025-05-10T18:27:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1q7zTHG2LSZAQ//VBCYfnbX0SOg18DDE55DvNi9Dw8xS+uSMCei2/h99c5M
        9ULIUtARCSI/F7DkG+YGaC88STK24owLsmKTc/ReO4hYTM0bHFjOc3Ze8Hvw7le1
        DtR4M2XAo8S6jmXTyEyhBlXcNx4EBiz7q4O92X2RZVd9oARB5uBHqpvP733dWj1W
        R3Wni4QzXbnbu70boa4tg168kQOk6i3tJ0INi+UZzcIxDJEUDGAoHGR6fPD+3QZL
        gct8ziC5IjSnzwqrHbZUGJSir6OxuQQ0vvqJQ28z/Nn0v7rfTeVTVesfkCfl6nk5
        CvNnGO+LhDmMpYOMPIqj64BfXwps2Ncvxj/HamZ8Y7ErVBNPK4sr18NHyU2fDMXA
        IFj/2F2ztz/aaNQXAb7JSlj8hqe5ZeL5EOsbrFvTKeitYxeIRLm5tWzVbBnHK+Uc
        kBu+KMo0O5z9sPNKTwgcZH350i3Ha37z4kFhakeW1Fe4pBmSrQjUicQhPI8JS9Pk
        OCDQfxBv3Nz6d6c/oLcZXO9exNlv3tdI0oZFOsUbYkidcz3p856ebcVBa0R6VF2c
        mGaoDM2Ky1xtCmlYumviTnJdbFng7cGu40XnwBw8XEL3dqTVtHBQ+PJRBJd/ON54
        fYK+CPQ2Gd52K+Fbsnp4F6zrzSwGLTxjKbb7BzxiqsaU9Jvx0yxDO1eI3Pn2zUnU
        aAEJAhD2VH3bCOm1ylv5VPHEl+QcB97rHeuCS1QiMjZ8Pp3u5M7NNv21A7fpWCc6
        1pOl3kVKPs7ZP4hbLMnlXwhI3Fr8gtpjsitje4Re8zB/LOX4oYST0YwFlCdhtya+
        TZeE17jy5fun
        =+YW7
        -----END PGP MESSAGE-----
      fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
  encrypted_regex: ^(data|stringData|email)$
  version: 3.10.2
