apiVersion: v1
stringData:
    api-token: ENC[AES256_GCM,data:cK3P7QAxaYVInier0abxokzRYiMD5/eke6Ad/8li4BWHrECiyp3WRQ==,iv:6GgTaNZS46iN2W0RRsuLbGsfKCytqd8ES1cpqYwx3zk=,tag:oWolBhsx6g32uwvNzpRp8w==,type:str]
kind: Secret
metadata:
    name: internal-cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
sops:
    lastmodified: "2025-05-10T17:50:26Z"
    mac: ENC[AES256_GCM,data:LjJKLNNLfrvziSIPNikVgvd9D4ArMda5OLfrkVLd5iOpC+TArMuLeo+m150jjSKbdwYIE4QCe7iY4EonUn962PxEFQvWnGtUo5f70eVD+TX1EPLdf4gRqb2RLxuB73Euxr+mCqWkXhS8J+Y8Mk0A/MP7/m9G2bPB8RrDSnvXYnk=,iv:iKYWW5J3YRg7ZYv0PAAfNMKGgBrK6UpOTmsMz0tyjM0=,tag:GklbqzIqgldAxjqJN7bfuw==,type:str]
    pgp:
        - created_at: "2025-05-10T17:50:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZARAApx8Jcs8e1k2UtvjEbtBf/Y7KOcoigcO0QXDJifGhrFqc
            /g95wrYSo26zwya2GEsF6ORW4uyblHmKzwZPzsrlkBoPGM8lzOuu+ZYH3DFWlVxK
            lUocfJ6X7Kn2qELY+J2tJ7vzG4dMghs4bk1wknzSszT4PKGmDYK9JWoMtbvf8RFh
            XOayvaizZIPXunHoKKYSdzjdYACdDUExe8gfa8rAT6kVqn4iRGFoF3ZXEzjr8n1a
            QrclM73erd6TZPR6d39jRZ5Rh2O1WFoz6hZrcOrcQc55PY7SfauJ/4xiF4bgoQYG
            iCeCP3PcDwkFFYZ3J9TeNmB8d0bj5IBXL2X+CerCMK7/K6WYALJZQ23cajFBjJk5
            iOkxwfqlT4VTXRhwE/cApSh7dvF7ImPcHcyOmpPOfVnl6GnYEYRkGykO0B5Gg7Vj
            2gkyV43kt2DJdlFoeiqv9fXG1N0uycF8lxiXbI7H+wty9tdL7Y0k+ezSA3gO8HqY
            VujKq1wTVnu0f1dJdhHRbli/xNYaDCOJ3eVTZLAxh/gce8fo5yuFTG7KXliOvvEz
            RwbIHmnR3Quwuthr3KHYfr5P7COkRzDPE19Ftuyy01XX7zKgLI2ba3gBpEZjFwEG
            DpOArtAPxmOHW0lAcgQ7iQ35piQUGSDH6DYCVNXp1VptMIAcLZcVtBPRKReYEgvU
            aAEJAhCDIQhC3vCLFaATNVaKso81AB1NYaBTyr+FvySS5wI/uqQd/cpnOJJm/hNe
            G0ExueQU6Zhf8ac0bdTKIOcz40UV38m9PpSwQVWdKd5iIO15/pvYmzZCAQ8Ok0u2
            a+j5VjZOvXaw
            =dw1f
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    api-token: ENC[AES256_GCM,data:jAgKmMKBazh90lZcjl/517wssnE2qHa7sbkrrj0Qlwxo2odjnTCBNg==,iv:vHpqA9TUHAUSXkRpfSNURFqWyKuS4fUp0lhKkQflwNc=,tag:MDgE2mfZl2jcB9YYMSfZzQ==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
sops:
    lastmodified: "2025-05-10T17:50:26Z"
    mac: ENC[AES256_GCM,data:LjJKLNNLfrvziSIPNikVgvd9D4ArMda5OLfrkVLd5iOpC+TArMuLeo+m150jjSKbdwYIE4QCe7iY4EonUn962PxEFQvWnGtUo5f70eVD+TX1EPLdf4gRqb2RLxuB73Euxr+mCqWkXhS8J+Y8Mk0A/MP7/m9G2bPB8RrDSnvXYnk=,iv:iKYWW5J3YRg7ZYv0PAAfNMKGgBrK6UpOTmsMz0tyjM0=,tag:GklbqzIqgldAxjqJN7bfuw==,type:str]
    pgp:
        - created_at: "2025-05-10T17:50:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1q7zTHG2LSZARAApx8Jcs8e1k2UtvjEbtBf/Y7KOcoigcO0QXDJifGhrFqc
            /g95wrYSo26zwya2GEsF6ORW4uyblHmKzwZPzsrlkBoPGM8lzOuu+ZYH3DFWlVxK
            lUocfJ6X7Kn2qELY+J2tJ7vzG4dMghs4bk1wknzSszT4PKGmDYK9JWoMtbvf8RFh
            XOayvaizZIPXunHoKKYSdzjdYACdDUExe8gfa8rAT6kVqn4iRGFoF3ZXEzjr8n1a
            QrclM73erd6TZPR6d39jRZ5Rh2O1WFoz6hZrcOrcQc55PY7SfauJ/4xiF4bgoQYG
            iCeCP3PcDwkFFYZ3J9TeNmB8d0bj5IBXL2X+CerCMK7/K6WYALJZQ23cajFBjJk5
            iOkxwfqlT4VTXRhwE/cApSh7dvF7ImPcHcyOmpPOfVnl6GnYEYRkGykO0B5Gg7Vj
            2gkyV43kt2DJdlFoeiqv9fXG1N0uycF8lxiXbI7H+wty9tdL7Y0k+ezSA3gO8HqY
            VujKq1wTVnu0f1dJdhHRbli/xNYaDCOJ3eVTZLAxh/gce8fo5yuFTG7KXliOvvEz
            RwbIHmnR3Quwuthr3KHYfr5P7COkRzDPE19Ftuyy01XX7zKgLI2ba3gBpEZjFwEG
            DpOArtAPxmOHW0lAcgQ7iQ35piQUGSDH6DYCVNXp1VptMIAcLZcVtBPRKReYEgvU
            aAEJAhCDIQhC3vCLFaATNVaKso81AB1NYaBTyr+FvySS5wI/uqQd/cpnOJJm/hNe
            G0ExueQU6Zhf8ac0bdTKIOcz40UV38m9PpSwQVWdKd5iIO15/pvYmzZCAQ8Ok0u2
            a+j5VjZOvXaw
            =dw1f
            -----END PGP MESSAGE-----
          fp: 733981EC713BBFDBAAD9E5FB77E29A7F07D187AC
    encrypted_regex: ^(data|stringData|email)$
    version: 3.10.2
