---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 8h
  timeout: 10m
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    hubble:
      ui:
        enabled: true
      relay:
        enabled: true
    envoy:
      enabled: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: cilium-alert
  namespace: flux-system
spec:
  summary: "Cilium"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: 'cilium'
      namespace: kube-system
    - kind: HelmChart
      name: 'kube-system-cilium'
      namespace: kube-system
    - kind: HelmRelease
      name: 'cilium'
      namespace: kube-system
