---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 8h
  timeout: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: csi-driver-nfs
  namespace: kube-system
spec:
  chart:
    spec:
      chart: csi-driver-nfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: csi-driver-nfs-alert
  namespace: flux-system
spec:
  summary: "CSI Driver NFS"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: 'csi-driver-nfs'
      namespace: kube-system
    - kind: HelmChart
      name: 'kube-system-csi-driver-nfs'
      namespace: kube-system
    - kind: HelmRelease
      name: 'csi-driver-nfs'
      namespace: kube-system
