---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: intra-namespace-allow-ingress
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: longhorn-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traefik-allow-ingress
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webhook-ui-allow-ingress
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 2049
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 9501
        - protocol: TCP
          port: 9502
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 8h
  timeout: 10m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 30m
  targetNamespace: longhorn-system
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.homelab-peej.dev
      tls: true
      tlsSecret: longhorn-internal-tls-secret
    persistence:
      defaultClass: false
      reclaimPolicy: Retain
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-internal-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.homelab-peej.dev
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: longhorn-alert
  namespace: flux-system
spec:
  summary: "Longhorn"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: longhorn-system
    - kind: HelmChart
      name: '*'
      namespace: longhorn-system
    - kind: HelmRelease
      name: '*'
      namespace: longhorn-system
