---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg
spec:
  interval: 8h
  timeout: 10m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: cnpg
  namespace: cnpg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  values:
    resources:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
        memory: 80Mi
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: cnpg-alert
  namespace: flux-system
spec:
  summary: "CNPG Operator"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: cnpg
    - kind: HelmChart
      name: '*'
      namespace: cnpg
    - kind: HelmRelease
      name: '*'
      namespace: cnpg
