---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 8h
  timeout: 10m
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: reloader
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: reloader
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    reloader:
      deployment:
        resources:
          requests:
            cpu: 1m
            memory: 24Mi
          limits:
            memory: 48Mi
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: reloader-alert
  namespace: flux-system
spec:
  summary: "Reloader"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: reloader
    - kind: HelmChart
      name: '*'
      namespace: reloader
    - kind: HelmRelease
      name: '*'
      namespace: reloader
