---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-internal-certificate
  namespace: traefik
spec:
  secretName: traefik-dashboard-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - traefik-dashboard.homelab-peej.dev
