---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 8h
  timeout: 10m
  url: https://headlamp-k8s.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: headlamp
  namespace: headlamp
spec:
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - hosts: headlamp.homelab-peej.dev
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: headlamp-internal-tls-secret
          hosts:
            - headlamp.homelab-peej.dev
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-internal-certificate
  namespace: headlamp
spec:
  secretName: headlamp-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - headlamp.homelab-peej.dev
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: headlamp-server-alert
  namespace: flux-system
spec:
  summary: "Headlamp"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: headlamp
    - kind: HelmChart
      name: '*'
      namespace: headlamp
    - kind: HelmRelease
      name: '*'
      namespace: headlamp
