---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: metallb
  namespace: metallb
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: 0.15.2
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: metallb
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    controller:
      resources:
        requests:
          cpu: 22m
          memory: 95Mi
        limits:
          memory: 95Mi
    speaker:
      resources:
        requests:
          cpu: 13m
          memory: 45Mi
        limits:
          memory: 45Mi
      frr:
        enabled: false
