---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-internal-certificate
  namespace: homepage
spec:
  secretName: homepage-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - www.homelab-peej.dev
