---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myspeed
  namespace: myspeed
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
