---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
      version: 0.10.8
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: authelia
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    pod:
      kind: 'Deployment'
      annotations:
        reloader.stakater.com/auto: "true"
      selectors:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: 'In'
                        values:
                          - authelia
                  topologyKey: kubernetes.io/hostname
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      extraVolumeMounts:
        - name: config-file
          mountPath: /config/users_database.yml
          subPath: users_database.yml
      extraVolumes:
        - name: config-file
          configMap:
            name: authelia-user-config
      resources:
        requests:
          cpu: 1m
          memory: 53Mi
        limits:
          cpu: ~
          memory: 53Mi
    configMap:
      access_control:
        default_policy: 'one_factor'
      authentication_backend:
        file:
          enabled: true
      session:
        cookies:
          - subdomain: auth
            domain: homelab-peej.dev
        redis:
          enabled: true
          deploy: true
          host: 'authelia-authelia-redis-master.authelia.svc.cluster.local'
      notifier:
        filesystem:
          enabled: true
      storage:
        local:
          enabled: true
      password_policy:
        sdandard:
          enabled: true
          min_length: 32
          require_uppercase: true
          require_lowercase: true
          require_number: true
          require_special: true
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
    redis:
      master:
        resources:
          requests:
            cpu: 12m
            memory: 12Mi
          limits:
            cpu: ~
            memory: 12Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: replace
                path: /spec/replicas
                value: 2
