---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-server
  namespace: ping-server
  labels:
    app.kubernetes.io/name: ping-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ping-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping-server
    spec:
      containers:
        - name: ping-server
          image: ghcr.io/homelab-peej/ping-server:0.1.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
      nodeSelector:
        kubernetes.io/arch: arm64
