---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ping-server
  namespace: ping-server
  labels:
    app.kubernetes.io/name: ping-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ping-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping-server
    spec:
      containers:
        - name: ping-server
          image: ghcr.io/homelab-peej/ping-server:0.2.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: /startz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 2
