---
apiVersion: v1
kind: Service
metadata:
  name: ping-server
  namespace: ping-server
  labels:
    app.kubernetes.io/name: ping-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ping-server
