---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-internal-certificate
  namespace: jellyfin
spec:
  secretName: jellyfin-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.homelab-peej.dev
