---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app actual
  namespace: flux-system
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/part-of: &namespace actual
spec:
  dependsOn:
    - name: flux-system
      namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/namespace: *namespace
  interval: 4h
  path: ./kubernetes/apps/actual/app
  prune: false
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 10m
  wait: false
