---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 1h
  timeout: 10m
  url: https://stakater.github.io/stakater-charts
