---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: reloader
      version: 2.1.3
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: reloader
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    fullnameOverride: reloader
    nameOverride: reloader
    reloader:
      deployment:
        resources:
          requests:
            cpu: 1m
            memory: 150Mi
          limits:
            memory: 150Mi
