---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: reflector
  namespace: flux-system
spec:
  summary: "Reflector"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: OCIRepository
      name: '*'
      namespace: reflector
    - kind: HelmRelease
      name: '*'
      namespace: reflector
