---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 9.1.26
  url: oci://ghcr.io/emberstack/helm-charts/reflector
