---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
      version: 0.10.10
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 5m
  targetNamespace: authelia
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    nameOverride: 'authelia'
    pod:
      kind: 'Deployment'
      revisionHistoryLimit: 3
      annotations:
        reloader.stakater.com/auto: "true"
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      extraVolumeMounts:
        - name: config-file
          mountPath: /config/users_database.yml
          subPath: users_database.yml
      extraVolumes:
        - name: config-file
          configMap:
            name: authelia-user-config
      resources:
        requests:
          cpu: 10m
          memory: 150Mi
        limits:
          cpu: ~
          memory: 150Mi
    configMap:
      access_control:
        default_policy: 'one_factor'
      authentication_backend:
        file:
          enabled: true
        password_reset:
          disable: true
        password_change:
          disable: true
      session:
        cookies:
          - subdomain: auth
            domain: homelab-peej.dev
        redis:
          enabled: true
          deploy: true
          host: 'authelia-authelia-redis-master.authelia.svc.cluster.local'
      notifier:
        filesystem:
          enabled: true
      storage:
        local:
          enabled: true
      password_policy:
        standard:
          enabled: true
          min_length: 32
          require_uppercase: true
          require_lowercase: true
          require_number: true
          require_special: true
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
    redis:
      master:
        resources:
          requests:
            cpu: 14m
            memory: 16Mi
          limits:
            cpu: ~
            memory: 16Mi
