---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: authelia
  namespace: authelia
spec:
  chart:
    spec:
      chart: authelia
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: authelia
      version: 0.10.12
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 5m
  targetNamespace: authelia
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    nameOverride: 'authelia'
    pod:
      kind: 'Deployment'
      revisionHistoryLimit: 3
      annotations:
        reloader.stakater.com/auto: "true"
      selectors:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: 'In'
                        values:
                          - authelia
                  topologyKey: kubernetes.io/hostname
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      extraVolumeMounts:
        - name: config-file
          mountPath: /config/users_database.yml
          subPath: users_database.yml
        - name: secret
          readOnly: true
          mountPath: /config/secrets
      extraVolumes:
        - name: config-file
          configMap:
            name: authelia-user-config
        - name: secret
          projected:
            sources:
              - secret:
                  name: authelia-app
                  items:
                    - key: password
                      path: POSTGRES_PASSWORD
      resources:
        requests:
          cpu: 21m
          memory: 300Mi
        limits:
          cpu: ~
          memory: 300Mi
      env:
        - name: TZ
          value: America/Chicago
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
          value: /config/secrets/POSTGRES_PASSWORD
    configMap:
      access_control:
        default_policy: 'one_factor'
      authentication_backend:
        file:
          enabled: true
        password_reset:
          disable: true
        password_change:
          disable: true
      session:
        cookies:
          - subdomain: auth
            domain: homelab-peej.dev
        redis:
          enabled: true
          deploy: true
          host: 'authelia-authelia-redis-master.authelia.svc.cluster.local'
      notifier:
        filesystem:
          enabled: true
      storage:
        postgres:
          enabled: true
          deploy: false
          address: "tcp://authelia-rw:5432"
          database: "authelia"
          username: "authelia"
          ssl:
            mode: disable
          password:
            disabled: true
      password_policy:
        standard:
          enabled: true
          min_length: 32
          require_uppercase: true
          require_lowercase: true
          require_number: true
          require_special: true
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteMany
    redis:
      master:
        resources:
          requests:
            cpu: 14m
            memory: 16Mi
          limits:
            cpu: ~
            memory: 16Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: replace
                path: /spec/replicas
                value: 2
