---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-internal-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn.homelab-peej.dev
