---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  chart:
    spec:
      chart: spegel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spegel
      version: 0.2.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: spegel
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    spegel:
      containerdSock: "/run/k3s/containerd/containerd.sock"
      containerdContentPath: "/var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content"
