---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-internal-certificate
  namespace: prometheus
spec:
  secretName: grafana-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.homelab-peej.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-internal-certificate
  namespace: prometheus
spec:
  secretName: prometheus-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.homelab-peej.dev
