---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-internal-certificate
  namespace: headlamp
spec:
  secretName: headlamp-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - headlamp.homelab-peej.dev
