---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim
  namespace: valheim
  labels:
    app.kubernetes.io/name: valheim
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: valheim
  template:
    metadata:
      name: valheim
      labels:
        app.kubernetes.io/name: valheim
    spec:
      containers:
        - name: valheim
          image: ghcr.io/lloesche/valheim-server:sha-20e6258
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Chicago"
            - name: SERVER_NAME
              value: "Mjolnir"
            - name: SERVER_PORT
              value: "2456"
            - name: WORLD_NAME
              value: "Valhalla"
            - name: SERVER_PASS
              valueFrom:
                secretKeyRef:
                  name: valheim-config
                  key: SERVER_PASS
            - name: SERVER_PUBLIC
              value: "false"
            - name: UPDATE_CRON
              value: "0 6 * * *"
            - name: UPDATE_IF_IDLE
              value: "true"
            - name: RESTART_CRON
              value: "0 4 * * *"
            - name: RESTART_IF_IDLE
              value: "true"
            - name: BACKUPS
              value: "true"
            - name: BACKUPS_CRON
              value: "0 2 * * *"
            - name: BACKUPS_DIRECTORY
              value: "/config/backups"
            - name: BACKUPS_MAX_AGE
              value: "14"
            - name: BACKUPS_MAX_COUNT
              value: "14"
            - name: BACKUPS_IF_IDLE
              value: "true"
            - name: BACKUPS_ZIP
              value: "true"
            - name: VALHEIM_PLUS
              value: "false"
            - name: VALHEIM_PLUS_REPO
              value: "Grantapher/ValheimPlus"
            - name: VALHEIM_PLUS_RELEASE
              value: "latest"
            - name: BEPINEX
              value: "false"
            - name: STATUS_HTTP
              value: "true"
            - name: STATUS_HTTP_PORT
              value: "80"
            - name: STATUS_HTTP_CONF
              value: "/config/httpd.conf"
            - name: STATUS_HTTP_HTDOCS
              value: "/opt/valheim/htdocs"
          ports:
            - containerPort: 2456
              protocol: UDP
            - containerPort: 2457
              protocol: UDP
          resources:
            requests:
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /opt/valheim
      runtimeClassName: nvidia
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: data
          persistentVolumeClaim:
            claimName: data
