---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.12.2
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  values:
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 50Mi
