---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 8h
  timeout: 10m
  url: https://helm.ngc.nvidia.com/nvidia
