---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 3
  dataPools:
    - name: tank
      failureDomain: osd
      replicated:
        size: 3
      parameters:
        pg_num: "64"
        pgp_num: "64"
      crushRoot: default
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
