---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephConfig:
    global:
      osd_pool_default_size: "1"
      mon_warn_on_pool_no_redundancy: "false"
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.2
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mgr:
    count: 3
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    allowDeviceClassUpdate: true
    allowOsdCrushWeightUpdate: false
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: k8s-12-f8g37
        devices:
          - name: "/dev/disk/by-id/ata-WDC_WD161KFGX-68AFPN0_2BKEPG9T" # /dev/sda
          - name: "/dev/disk/by-id/ata-ST16000NM001G-2KK103_ZL2EG04P" # /dev/sdb
          - name: "/dev/disk/by-id/ata-WDC_WD80EFAX-68LHPN0_7SGG5M6C" # /dev/sdc
          - name: "/dev/disk/by-id/ata-ST16000NM001G-2KK103_ZL2DWHTG" # /dev/sdd
          - name: "/dev/disk/by-id/ata-WDC_WD80EFAX-68LHPN0_7SGG7UEC" # /dev/sde
          - name: "/dev/disk/by-id/ata-WDC_WD80EFAX-68LHPN0_7SGKD3YC" # /dev/sdf
          - name: "/dev/disk/by-id/ata-WDC_WD80EFAX-68LHPN0_7SGG58KC" # /dev/sdg
          - name: "/dev/disk/by-id/ata-WDC_WD80EFAX-68LHPN0_7SGG5HZC" # /dev/sdh
