---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-internal-certificate
  namespace: tautulli
spec:
  secretName: tautulli-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - tautulli.homelab-peej.dev
