---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: tautulli
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
