---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actual-internal-certificate
  namespace: actual
spec:
  secretName: actual-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - actual.homelab-peej.dev
