---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8096
    - name: https
      port: 8920
  selector:
    app.kubernetes.io/name: jellyfin
