---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: unpoller
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unpoller
      app_name: unpoller
  template:
    metadata:
      labels:
        app: unpoller
        app_name: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.15.3
          imagePullPolicy: Always
          env:
            - name: UP_UNIFI_DEFAULT_URL
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-url
            - name: UP_UNIFI_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-user
            - name: UP_UNIFI_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-pass
            - name: UP_UNIFI_DEFAULT_SAVE_DPI
              value: "true"
          resources:
            requests:
              cpu: 2m
              memory: 45Mi
            limits:
              memory: 45Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
      restartPolicy: Always
