---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: unpoller
  labels:
    app: unpoller
    app_name: unpoller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9130
  selector:
    app_name: unpoller
