---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kavita-internal-certificate
  namespace: kavita
spec:
  secretName: kavita-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - kavita.homelab-peej.dev
