---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb-books
spec:
  capacity:
    storage: 50Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0555
    - file_mode=0555
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-mjolnir.homelab-peej.dev/media##
    volumeAttributes:
      source: //mjolnir.homelab-peej.dev/media
    nodeStageSecretRef:
      name: media-creds
      namespace: kavita
