---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-media
  namespace: kavita
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: pv-smb-books
  resources:
    requests:
      storage: 50Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: kavita
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
