---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: arc-runners-alert
  namespace: flux-system
spec:
  summary: "Action Runners"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: OCIRepository
      name: '*'
      namespace: arc-runners
    - kind: HelmRelease
      name: '*'
      namespace: arc-runners
