---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-controller
  namespace: arc-systems
spec:
  chartRef:
    kind: OCIRepository
    name: arc-runner-controller
  interval: 24h
  values:
    requests:
      cpu: 1m
      memory: 32Mi
    limits:
      memory: 32Mi
  # ARC workaround https://github.com/fluxcd/flux2/issues/4910#issuecomment-2286684282
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |
              - op: replace
                path: /spec/template/metadata/labels/app.kubernetes.io~1version
                value: latest
