---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: arc-runner-controller
  namespace: arc-systems
  annotations:
    api.fluxcd.io/upgrade: "v2.6.0"
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 0.12.1
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
