---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
