---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
