---
apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mealie
      app_name: mealie
  template:
    metadata:
      labels:
        app: mealie
        app_name: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.8.0
          imagePullPolicy: Always
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: openai-api-key
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-from-email
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-host
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-password
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-user
          command:
            - /app/run.sh
          volumeMounts:
            - mountPath: /app/data
              name: mealie
          workingDir: /
          resources:
            requests:
              cpu: 2m
              memory: 428Mi
            limits:
              memory: 428Mi
      restartPolicy: Always
      volumes:
        - name: mealie
          persistentVolumeClaim:
            claimName: mealie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
    app_name: mealie
spec:
  type: ClusterIP
  ports:
    - name: web-ui
      port: 9000
  selector:
    app_name: mealie
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-private
  namespace: mealie
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mealie.homelab-peej.dev
      secretName: mealie-internal-tls-secret
  rules:
    - host: mealie.homelab-peej.dev
      http:
        paths:
          - backend:
              service:
                name: mealie
                port:
                  number: 9000
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-internal-certificate
  namespace: mealie
spec:
  secretName: mealie-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.homelab-peej.dev
