---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 1.18.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 10m
  targetNamespace: cilium
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    operator:
      resources:
        requests:
          cpu: 2m
          memory: 160Mi
        limits:
          memory: 160Mi
    hubble:
      ui:
        enabled: true
        backend:
          resources:
            requests:
              cpu: 2m
              memory: 50Mi
            limits:
              memory: 50Mi
        frontend:
          resources:
            requests:
              cpu: 1m
              memory: 10Mi
            limits:
              memory: 10Mi
        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: cilium-hubble-dashboard-auth@kubernetescrd
          hosts:
            - hubble.homelab-peej.dev
          tls:
            - secretName: hubble-internal-tls-secret
              hosts:
                - hubble.homelab-peej.dev
      relay:
        enabled: true
        resources:
          requests:
            cpu: 1m
            memory: 45Mi
          limits:
            memory: 45Mi
    envoy:
      enabled: true
      resources:
        requests:
          cpu: 19m
          memory: 74Mi
        limits:
          memory: 74Mi
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
