---
apiVersion: v1
kind: Namespace
metadata:
  name: actual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: actual
  labels:
    app: actual
    app_name: actual
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app_name: actual
  template:
    metadata:
      name: actual
      labels:
        app: actual
        app_name: actual
    spec:
      containers:
        - name: actual
          image: ghcr.io/actualbudget/actual:25.3.1@sha256:58fecd9088b73ffe402450f51eff488036cdc8ca570650be38ad2bbabbfe193b
          imagePullPolicy: Always
          volumeMounts:
            - name: actual-data
              mountPath: /data
          resources:
            requests:
              cpu: 26m
              memory: 170Mi
            limits:
              memory: 170Mi
      volumes:
        - name: actual-data
          persistentVolumeClaim:
            claimName: actual-data
---
apiVersion: v1
kind: Service
metadata:
  name: actual
  namespace: actual
  labels:
    app_name: actual
spec:
  type: ClusterIP
  ports:
    - name: web-ui
      port: 5006
  selector:
    app_name: actual
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-private
  namespace: actual
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - actual.homelab-peej.dev
      secretName: actual-internal-tls-secret
  rules:
    - host: actual.homelab-peej.dev
      http:
        paths:
          - backend:
              service:
                name: actual
                port:
                  number: 5006
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: actual-internal-certificate
  namespace: actual
spec:
  secretName: actual-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - actual.homelab-peej.dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: actual
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
