---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
    app_name: homeassistant
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app_name: homeassistant
  template:
    metadata:
      name: homeassistant
      labels:
        app: homeassistant
        app_name: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2025.3.4
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: hass-config
              mountPath: /config
            - name: config-file
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            requests:
              cpu: 2m
              memory: 454Mi
            limits:
              memory: 454Mi
        - name: zwave-js-ui
          image: ghcr.io/zwave-js/zwave-js-ui:10.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
            - containerPort: 3000
              name: websocket
              protocol: TCP
          resources:
            requests:
              cpu: 2m
              memory: 234Mi
            limits:
              memory: 234Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          volumeMounts:
            - mountPath: /dev/zwave
              name: zwavestick
            - mountPath: /usr/src/app/store
              name: zwave-data
      nodeSelector:
        kubernetes.io/hostname: k8s-pi-3
      volumes:
        - name: hass-config
          persistentVolumeClaim:
            claimName: hass-config
        - name: config-file
          configMap:
            name: homeassistant-configuration
        - name: zwavestick
          hostPath:
            path: /dev/serial/by-id/usb-0658_0200-if00
            type: CharDevice
        - name: zwave-data
          persistentVolumeClaim:
            claimName: zwave-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-configuration
  namespace: homeassistant
data:
  configuration.yaml: |
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app_name: homeassistant
spec:
  type: ClusterIP
  ports:
    - name: web-ui
      port: 8123
    - name: websocket
      port: 3000
    - name: zwave-web-ui
      port: 8091
  selector:
    app_name: homeassistant
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-private
  namespace: homeassistant
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - homeassistant.homelab-peej.dev
      secretName: homeassistant-internal-tls-secret
  rules:
    - host: homeassistant.homelab-peej.dev
      http:
        paths:
          - backend:
              service:
                name: homeassistant
                port:
                  number: 8123
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-internal-certificate
  namespace: homeassistant
spec:
  secretName: homeassistant-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - homeassistant.homelab-peej.dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwave-private
  namespace: homeassistant
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zwave.homelab-peej.dev
      secretName: zwave-internal-tls-secret
  rules:
    - host: zwave.homelab-peej.dev
      http:
        paths:
          - backend:
              service:
                name: homeassistant
                port:
                  number: 8091
            path: /
            pathType: Prefix
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zwave-internal-certificate
  namespace: homeassistant
spec:
  secretName: zwave-internal-tls-secret
  issuerRef:
    name: internal-cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - zwave.homelab-peej.dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
