apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mealie
      app_name: mealie
  template:
    metadata:
      labels:
        app: mealie
        app_name: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:latest # {"$imagepolicy": "mealie:mealie"}
          imagePullPolicy: Always
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: openai-api-key
            - name: SMTP_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-from-email
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-host
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-password
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-config
                  key: smtp-user
          command:
            - /app/run.sh
          volumeMounts:
            - mountPath: /app/data
              name: mealie
          workingDir: /
          resources:
            requests:
              cpu: "1m"
              memory: "350Mi"
            limits:
              memory: "500Mi"
      restartPolicy: Always
      volumes:
        - name: mealie
          persistentVolumeClaim:
            claimName: mealie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: mealie
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
    app_name: mealie
spec:
  type: LoadBalancer
  ports:
    - name: web-ui
      targetPort: 9000
      port: 80
  selector:
    app_name: mealie
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mealie
  namespace: mealie
spec:
  image: ghcr.io/mealie-recipes/mealie
  interval: 6h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mealie
  namespace: mealie
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: mealie
  namespace: mealie
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: peej11-bot@users.noreply.github.com
        name: peej11-bot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./self-hosted
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: mealie-alert
  namespace: flux-system
spec:
  summary: "Mealie"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: ImageRepository
      name: '*'
      namespace: mealie
    - kind: ImagePolicy
      name: '*'
      namespace: mealie
    - kind: ImageUpdateAutomation
      name: '*'
      namespace: mealie
