apiVersion: v1
kind: Namespace
metadata:
  name: tautulli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: tautulli
  labels:
    app: tautulli
    app_name: tautulli
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app_name: tautulli
  template:
    metadata:
      name: tautulli
      labels:
        app: tautulli
        app_name: tautulli
    spec:
      containers:
        - name: tautulli
          image: ghcr.io/tautulli/tautulli:latest # {"$imagepolicy": "tautulli:tautulli"}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PUID
              value: "49582"
            - name: PGID
              value: "3004"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: ".5m"
              memory: "180Mi"
            limits:
              memory: "256Mi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: tautulli
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: tautulli
  labels:
    app_name: tautulli
spec:
  type: LoadBalancer
  ports:
  - name: web-ui
    targetPort: 8181
    port: 80
  selector:
    app_name: tautulli
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tautulli
  namespace: tautulli
spec:
  image: ghcr.io/tautulli/tautulli
  interval: 6h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: tautulli
  namespace: tautulli
spec:
  imageRepositoryRef:
    name: tautulli
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: tautulli
  namespace: tautulli
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: peej11-bot@users.noreply.github.com
        name: peej11-bot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./self-hosted
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: tautulli-alert
  namespace: flux-system
spec:
  summary: "Tautulli"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: ImageRepository
      name: '*'
      namespace: tautulli
    - kind: ImagePolicy
      name: '*'
      namespace: tautulli
    - kind: ImageUpdateAutomation
      name: '*'
      namespace: tautulli
