---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1m
  chart:
    spec:
      chart: spegel
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: spegel
  values:
    spegel:
      containerdSock: "/run/k3s/containerd/containerd.sock"
      containerdContentPath: "/var/lib/rancher/k3s/agent/containerd/io.containerd.content.v1.content"
