---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: csi-driver-smb
spec:
  interval: 1h
  timeout: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
