name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flux:
    runs-on: arc-runner-set
    if: github.repository == 'homelab-peej/k8s-at-home'
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Check for updates
        id: update
        run: |
          flux install \
            --export > ./kubernetes/apps/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          VERSION_NUMBER="$(flux -v | sed 's/flux version //g')"
          echo "flux_version=$VERSION" >> $GITHUB_ENV
          echo "flux_version_number=$VERSION_NUMBER" >> $GITHUB_ENV
      - name: Update Readme
        run: sed -i 's/Flux\/[0-9.]\+\(-rc.[0-9]\)\?\/blue/Flux\/${{ env.flux_version_number }}\/blue/g' ${{ github.workspace }}/README.md
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-flux
          author: Peej11-Bot <198817040+Peej11-Bot@users.noreply.github.com>
          committer: Peej11-Bot <198817040+Peej11-Bot@users.noreply.github.com>
          commit-message: Update Flux to ${{ env.flux_version }}
          title: Update Flux to ${{ env.flux_version }}
          body: |
            Update Flux to ${{ env.flux_version }}
            Verify any API changes at https://github.com/fluxcd/flux2/releases/latest and add manifest changes to this branch before merging
          reviewers: |
            Peej11
