name: yamllint
on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'
jobs:
  yamllint:
    runs-on: yamllint-runner-set
    if: github.repository == 'homelab-peej/k8s-at-home'
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run yamllint
        run: for i in ${{ github.workspace }}; do yamllint -d '{"extends":"default","ignore":"flux-system/\n.github/\n.secrets/","rules":{"line-length":"disable","comments":"disable"}}' "$i"; done
        shell: bash
