name: yamllint
on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'
jobs:
  yamllint:
    runs-on: arc-runner-set
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install yamllint
        run: sudo apt update && sudo apt install -y python3-pip && pip install yamllint
        shell: bash
      - name: Run yamllint
        run: for i in ${{ github.workspace }}; do ~/.local/bin/yamllint -d '{"extends":"default","ignore":"flux-system/\n.github/\n.secrets/","rules":{"line-length":"disable","comments":"disable"}}' "$i"; done
        shell: bash
