---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 8h
  timeout: 10m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  timeout: 30m
  values:
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 50Mi
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: metrics-server-alert
  namespace: flux-system
spec:
  summary: "Metrics Server"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
      namespace: metrics-server
    - kind: HelmChart
      name: '*'
      namespace: metrics-server
    - kind: HelmRelease
      name: '*'
      namespace: metrics-server
