---
apiVersion: v1
kind: Namespace
metadata:
  name: unpoller
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: unpoller
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-allow-ingress
  namespace: unpoller
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prometheus
      ports:
        - protocol: TCP
          port: 9130
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: unpoller
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unpoller
      app_name: unpoller
  template:
    metadata:
      labels:
        app: unpoller
        app_name: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.14.1 # {"$imagepolicy": "unpoller:unpoller"}
          imagePullPolicy: Always
          env:
            - name: UP_UNIFI_DEFAULT_URL
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-url
            - name: UP_UNIFI_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-user
            - name: UP_UNIFI_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-pass
            - name: UP_UNIFI_DEFAULT_SAVE_DPI
              value: "true"
          resources:
            requests:
              cpu: 2m
              memory: 45Mi
            limits:
              memory: 45Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: unpoller
  labels:
    app: unpoller
    app_name: unpoller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9130
  selector:
    app_name: unpoller
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: unpoller
  namespace: unpoller
spec:
  image: ghcr.io/unpoller/unpoller
  interval: 6h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: unpoller
  namespace: unpoller
spec:
  imageRepositoryRef:
    name: unpoller
  policy:
    semver:
      range: '>=2.0.0 <3.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: unpoller
  namespace: unpoller
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: peej11-bot@users.noreply.github.com
        name: peej11-bot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./metrics
    strategy: Setters
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: unpoller-alert
  namespace: flux-system
spec:
  summary: "Unpoller"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: ImageRepository
      name: '*'
      namespace: unpoller
    - kind: ImagePolicy
      name: '*'
      namespace: unpoller
    - kind: ImageUpdateAutomation
      name: '*'
      namespace: unpoller
