---
apiVersion: v1
kind: Namespace
metadata:
  name: unpoller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: unpoller
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unpoller
      app_name: unpoller
  template:
    metadata:
      labels:
        app: unpoller
        app_name: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.14.1@sha256:9ba73b1793ef332ae9b4b719ef0fc09f231d6276bc7b721cbb47961ed7792961
          imagePullPolicy: Always
          env:
            - name: UP_UNIFI_DEFAULT_URL
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-url
            - name: UP_UNIFI_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-user
            - name: UP_UNIFI_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: unpoller-config
                  key: unifi-pass
            - name: UP_UNIFI_DEFAULT_SAVE_DPI
              value: "true"
          resources:
            requests:
              cpu: 2m
              memory: 45Mi
            limits:
              memory: 45Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: unpoller
  labels:
    app: unpoller
    app_name: unpoller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9130
  selector:
    app_name: unpoller
